name         'puppetlabs-ceilometer'
version      '4.0.0'
author       'eNovance and StackForge Contributors'
license      'Apache License 2.0'
summary      'Puppet module for OpenStack Ceilometer'
description  'Installs and configures OpenStack Ceilometer (Telemetry).'
project_page 'https://launchpad.net/puppet-ceilometer'
source       'https://github.com/stackforge/puppet-ceilometer'

dependency 'puppetlabs/inifile', '>=1.0.0 <2.0.0'
dependency 'puppetlabs/keystone', '>=4.0.0 <5.0.0'
dependency 'puppetlabs/stdlib', '>= 3.2.0'
dependency 'stackforge/openstacklib', '>=5.0.0'
